export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';


export const FETCH_INGREDIENT_PRICES = 'FETCH_INGREDIENT_PRICES';
export const FETCH_INGREDIENT_PRICES_FAILED = 'FETCH_INGREDIENT_PRICES_FAILED';
export const FETCH_INGREDIENT_PRICES_SUCCESS = 'FETCH_INGREDIENT_PRICES_SUCCESS';

export const PURCHASE_BURGER = 'PURCHASE_BURGER'; //SAGA
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';    
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS = 'FETCH_ORDERS'; //SAGA
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';


export const AUTH_USER = 'AUTH_USER'; 
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_AUTO_SUCCESS = 'AUTH_AUTO_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';


export const RESET_USER_CONTACT_DATA = 'RESET_USER_CONTACT_DATA';
export const FETCH_USER_CONTACT_DATA_SUCCESS = 'FETCH_USER_CONTACT_DATA_SUCCESS';
export const FETCH_USER_CONTACT_DATA_FAIL = 'FETCH_USER_CONTACT_DATA_FAIL';
export const FETCH_USER_CONTACT_DATA_START = 'FETCH_USER_CONTACT_DATA_START';